### ISSUE TITLE
Detail layers infinite synchronized clones.

### ISSUE THREAD

**Issue by TechnoLukas** [Zylann/godot_heightmap_plugin#415] opened 2023-12-10 15:13 UTC
**Describe the bug**
When I place a few "details" on synchronized i see a lot of synchronized clones of it around current terrain.
I edit main one, and all of clones around it are edited simultaneously.

**To Reproduce**
1. Create Terrain
2. Set scale to 0.1, 0.1, 0.1     (With scale 1 ,1, 1 the bug will be less visible due to visibility distance)
4. Add one detail layer
5. Place few of "details"
You will see a lot of clones around the terrain

**Demo project:**
[heightmap_plugin_bug.zip](https://github.com/Zylann/godot_heightmap_plugin/files/13628228/heightmap_plugin_bug.zip)

**Expected behavior:**
No "clones" around 

**Screenshots:**
visibility 100:
<img width="998" alt="image" src="https://github.com/Zylann/godot_heightmap_plugin/assets/110934679/2b188d41-8efb-4445-9ba0-8315a0db8a99">
visibility 500:
<img width="1459" alt="image" src="https://github.com/Zylann/godot_heightmap_plugin/assets/110934679/dea9988c-a23d-438b-9790-9baabfbfa421">
visibility 4337 (edited plugin max value)
<img width="1659" alt="image" src="https://github.com/Zylann/godot_heightmap_plugin/assets/110934679/07470ed4-9d83-4ad2-be0f-245869d7d2ed">

**Environment:**
- OS: [Windows 11]
- Godot version [4.2]
- Plugin version [1.3.7 dev]
- Renderer used: [Compatibility & Forward+]

**Comment by Zylann** [comment] 2023-12-10 16:54
Apparently if you change `map_scale` after painting details, the problem disappears

**Comment by TechnoLukas** [comment] 2023-12-10 17:28
No, it doesn't. Fly around and you will see that is it still there. It is just less visible due to visibility range. For debug purposes i set it up to 1000. 

https://github.com/Zylann/godot_heightmap_plugin/assets/110934679/39c9c227-0765-45cb-87e3-aef18d9ee071

**Comment by Zylann** [comment] 2023-12-10 17:28
Yeah I noticed. It appears to fix it but it comes back later.

**Comment by Zylann** [comment] 2023-12-10 17:37
Should be fixed in 42b861ee862aad62dfbac4ff2607b1da74c7cd4a

**Comment by TechnoLukas** [comment] 2023-12-10 18:06
Now there is no clones. So it is kinda fixed. Now there is a new problem:
When terrain scale is 0.1, 0.1, 0.1, newly created "detail layer" is not visible, i have to scale terrain to 1,1,1 and back to 0.1, 0.1,0.1  And i have to do it for every new "detail layer" .

https://github.com/Zylann/godot_heightmap_plugin/assets/110934679/557903a0-5c3c-4e3d-a0e3-f086e667c2a7

**Comment by Zylann** [comment] 2023-12-10 18:20
How are you adding detail layers? It works when I use the Add button in the bottom panel.

**Comment by TechnoLukas** [comment] 2023-12-10 18:25
Yeah, same.
**What i do:**
1. Create terrain with map scale 0.1 , 0.1, 0.1
2. Add details layer
3. Try to draw details, though they are not visible.
4. Scale map to 1,1,1
5. I see details are visible
6. Scale map to 0.1, 0.1, 0.1
7. Now they are visible too.

**Comment by Zylann** [comment] 2023-12-10 18:32
I can't reproduce it.

https://github.com/Zylann/godot_heightmap_plugin/assets/1311555/78be4087-f516-408e-af28-244ef1681143

**Comment by Zylann** [comment] 2023-12-10 19:02
I think it happens because you also set the terrain to be centered.

**Comment by Zylann** [comment] 2023-12-10 19:09
The second issue should be fixed in f5707d32840834574487cb862ac0b632b7c01520

**Comment by TechnoLukas** [comment] 2023-12-10 20:38
Yes, every issue described above is fixed. Confirmed.

**Closed** 2023-12-10 20:43 UTC
Labels: bug
