### ISSUE TITLE
Brightness of the terrain changes when normalmap is applied

### ISSUE THREAD

**Issue by kubajz22** [Zylann/godot_heightmap_plugin#210] opened 2020-11-04 02:05 UTC
**Describe the bug**
The brightness of the albedo color depends on whether the normalmap is in use or not. When you load a normalmap texture, the color of the terrain gets a bit lighter. It doesn't matter if the normalmap actually holds any meaningful information or is completely flat. PNG and JPG images behave pretty much the same.

**Screenshots**
Without normalmap:
![without_normalmap](https://user-images.githubusercontent.com/13995703/98060296-28bb4080-1e41-11eb-95d0-fb7858ee0694.png)

With normalmap:
![with_normalmap](https://user-images.githubusercontent.com/13995703/98060339-44bee200-1e41-11eb-9897-671df936bb40.png)

**Environment**
- OS: Linux mint 20
- Graphics card: nVidia GeForce GTX 1650 
- Godot version: 3.2.3-stable
- Plugin version: 1.4
- Renderer used: GLES3

**Comment by kubajz22** [comment] 2020-11-04 02:15
OK, I found the reason. The terrain actually just isn't affected by any DirectinalLight if it has no normal map.

**Comment by Zylann** [comment] 2020-11-05 18:58
Yes, this is the same as https://github.com/Zylann/godot_heightmap_plugin/issues/199
If you use the `Classic4` shader without the normalmaps it expects, lighting will be wrong. It should be correct if all slots have a normal map.

**Comment by Zylann** [comment] 2021-01-11 18:17
I'll close this since this is not a bug.

**Closed by Zylann** 2021-01-11 18:17 UTC
