### ISSUE TITLE
Cut holes tool isn't removing collision?

### ISSUE THREAD

**Issue by leksur** [Zylann/godot_heightmap_plugin#218] opened 2020-11-17 20:29 UTC
hey!

Just started playing around with this plugin (great work btw!). Looking to add a tunnel system, but the cut holes tool doesn't seem to be removing collision on the cut area. So, when I attempt to add a mesh for a tunnel, I basically collide with the entrance and cannot enter. Is this a bug, or am I forgetting something? 

Thanks!

**Comment by Zylann** [comment] 2020-11-17 21:46
This is a missing feature from Godot's physics engine (here Bullet Physics). To be properly supported, it would need a customization of the heightmap collider to discard vertices that are on a hole.

The only workaround for now is to play with collision layers and switch them around while entering or exiting the hole...

**Comment by Zylann** [comment] 2020-11-17 21:51
In fact this would be a duplicate of https://github.com/Zylann/godot_heightmap_plugin/issues/125

**Comment by leksur** [comment] 2020-11-17 22:11
Ah yes, ty ty. For some reason I wasn't able to find an existing issue when I searched.

**Closed** 2020-11-17 22:11 UTC
