### ISSUE TITLE
GNU/Linux doesn't seem to be 100% supported

### ISSUE THREAD

**Issue by Liemaeu** [Zylann/godot_heightmap_plugin#178] opened 2020-06-19 20:35 UTC
In the Editor everything works fine, but when I export the project the hterrain map doesn't have any textures.

When I open the project in the Godot engine I get the error "does not have a library for the current platform.". In addons/zylann.hterrain/native/factory.gd there is only Windows in the _supported_os.
In addons/zylann.hterrain/native/bin/ is only a win64 folder with a .dll, no linux with a .so library file.

I'm working on Ubuntu 20.04 (64 Bit).

**Comment by Calinou** [comment] 2020-06-19 21:17
You'll need to compile the native library from source. I believe Zylann only has access to a Windows PC, so they don't provide Linux libraries in the repository. (Moreover, uploading compiled libraries bloats the Git history, so it's better to avoid it when possible.)

**Comment by Liemaeu** [comment] 2020-06-19 21:33
Thx @Calinou 
How do I compile it? Anything else I have to change?

**Comment by Zylann** [comment] 2020-06-20 20:39
> does not have a library for the current platform

This doesn't prevent the plugin from working on Linux. It only means GDNative acceleration is not available, unless you indeed compile that part for Linux.
The error message is not supposed to show up, but it does anyways because of https://github.com/godotengine/godot/issues/38140

**Comment by Liemaeu** [comment] 2020-06-20 22:09
Thanks @Zylann !

Did I got it right?

cd godot-project/addons/zylann.hterrain/native
git submodule add https://github.com/GodotNativeTools/godot-cpp
git submodule update --init --recursive
cd godot-cpp
scons platform=linux generate_bindings=yes

Create the folder godot-project/addons/zylann.hterrain/native/bin/linux and copy godot-project/addons/zylann.hterrain/native/godot-cpp/bin/libgodot-cpp.linux.debug.64.a to godot-project/addons/zylann.hterrain/native/bin/linux/libgodot-cpp.linux.debug.64.a.
After this editing the file godot-project/addons/zylann.hterrain/native/factory.gd, in the _supported_os after the line "Windows": true I have to add the line: "X11": true
And then editing the file godot-project/addons/zylann.hterrain/native/hterrain.gdnlib, in the [entry] section after the line Windows.64 = "res://addons/zylann.hterrain/native/bin/win64/hterrain_native.dll" I have to add the line: X11.64 = "res://zylann.hterrain/native/bin/linux/libgodot-cpp.linux.debug.64.a"

**Comment by Zylann** [comment] 2020-06-20 22:15
> Create the folder godot-project/addons/zylann.hterrain/native/bin/linux and copy godot-project/addons/zylann.hterrain/native/godot-cpp/bin/libgodot-cpp.linux.debug.64.a to godot-project/addons/zylann.hterrain/native/bin/linux/libgodot-cpp.linux.debug.64.a.

You should not need to do this, I think it's done automatically by the build script.

> in the [entry] section after the line Windows.64 = "res://addons/zylann.hterrain/native/bin/win64/hterrain_native.dll" I have to add the line: X11.64 = "res://zylann.hterrain/native/bin/linux/libgodot-cpp.linux.debug.64.a"

It should not be a `.a`, it's a `.so`.

**Comment by Liemaeu** [comment] 2020-06-20 22:31
scons platform=linux generate_bindings=yes outputs the file to godot-project/addons/zylann.hterrain/native/godot-cpp/bin/. The only file in there is libgodot-cpp.linux.debug.64.a.

**Comment by Zylann** [comment] 2020-06-20 22:32
Yes, godot-cpp only outputs a `.a`, but it doesn't have to move somewhere else.

**Comment by Liemaeu** [comment] 2020-06-20 22:36
So this is not the library I am looking for?

**Comment by Zylann** [comment] 2020-06-20 22:39
Basically, you should not have to move anything. Files should already be produces where they should be when the SCons scripts have been run.

**Comment by Liemaeu** [comment] 2020-06-20 22:46
Ah, I think I got it. I need to got to godot-project/addons/zylann.hterrain/native/ and run: scons platform=linux
This will create the godot-project/addons/zylann.hterrain/native/bin/linux/libhterrain_native.so

But I really don't have to make any changes in the factory.gd and the hterrain.gdnlib?

**Comment by Zylann** [comment] 2020-06-20 23:01
The only changes you have to write is in `factory.gd` and `hterrain.gdnlib` yes.

**Comment by Liemaeu** [comment] 2020-06-20 23:56
Ok, I made a simple script for this:
https://github.com/Liemaeu/GDNative-linux-HeightMap/blob/master/GDNative-linux.sh
(you need to place it into the addons/zylann.hterrain/ folder into your project folder, make it executable with chmod +x GDNative-linux.sh and run it with ./GDNative-linux.sh).

**Comment by Liemaeu** [comment] 2020-06-21 00:35
Now when I open Godot I get the error: Couldn't load addon : ‚res://addons/zylann.hterrain/tools/plugin.gd‘. It seams to have an error in the source code. Please check syntax.

And the output:
` res://addons/zylann.hterrain/native/factory.gd:8 - Parse Error: ',' or '}' expected
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain_data.gd:11 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain.gd:7 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/tools/plugin.gd:5 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/native/factory.gd:8 - Parse Error: ',' or '}' expected
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain_data.gd:11 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain.gd:7 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/native/factory.gd:8 - Parse Error: ',' or '}' expected
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain_data.gd:11 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/zylann.hterrain/hterrain_resource_loader.gd:6 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 Script does not inherit a CustomResourceLoader: res://addons/zylann.hterrain/hterrain_resource_loader.gd.
 res://addons/zylann.hterrain/hterrain_resource_saver.gd:6 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 Script does not inherit a CustomResourceSaver: res://addons/zylann.hterrain/hterrain_resource_saver.gd`

**Comment by Zylann** [comment] 2020-06-21 01:37
Looks like you made a mistake when editing `factory.gd`?

**Comment by Liemaeu** [comment] 2020-06-21 09:16
I forgot to add a "," after the "Windows": true in the _supported_os, before adding "Linux": true.
Now it works.

I don't think this has something to do with the GDNative, but the texture of the HTerrain still doesn't export correctly. In my scene with the HTerrain I get this output:
` core/image.cpp:1884 - Loaded resource as image file, this will not work on export: 'res://Maps/Forest/data/normal.png'. Instead, import the image file as an Image resource and load it normally as a resource.
 core/image.cpp:1884 - Loaded resource as image file, this will not work on export: 'res://Maps/Forest/data/splat.png'. Instead, import the image file as an Image resource and load it normally as a resource.
 core/image.cpp:1884 - Loaded resource as image file, this will not work on export: 'res://Maps/Forest/data/color.png'. Instead, import the image file as an Image resource and load it normally as a resource.`

**Comment by Zylann** [comment] 2020-06-21 13:41
Those image warnings should also not prevent the plugin from working. Images get loaded this way for edition purposes, and I don't know yet how to get rid of the warnings: https://github.com/godotengine/godot/issues/24222

> the texture of the HTerrain still doesn't export correctly

You mean you exported the game and the terrain doesn't show up? Does it work in editor?

**Comment by Liemaeu** [comment] 2020-06-21 15:50
Yes, it is just the error messages. The exported game now has the textures. Thank you very much for your help!
Any chance of getting the GDNative library for Linux in future versions? The "platform not supported" error message and the not available acceleration is not a big deal, but that the textures don't work without it is quite bad.
(Maybe you could compile the GDNative on a virtual machine or e.g. with Docker. Or at least a note for Linux and macOS users in the README/description what to do)

**Comment by Zylann** [comment] 2020-06-21 15:54
> that the textures don't work without it is quite bad.

But you just said they worked actually? To be clear, the entire plugin should be functional even without GDNative (if not, that's a bug). The library is only there to make it faster.

> Any chance of getting the GDNative library for Linux in future versions?

I thought to do it through Travis CI or Github actions to get binaries on each platform, but I'm not experienced in these and didnt take the time to do it yet.

**Comment by Liemaeu** [comment] 2020-06-21 15:59
Now everything works fine.
Before compiling the GDNative library the HTerrain map had no textures in the exported game, only in the Godot editor.

**Comment by Zylann** [comment] 2020-06-21 16:01
> Before compiling the GDNative library the HTerrain map had no textures in the exported game, only in the Godot editor.

This is very strange because GDNative has nothing to do with texture import Oo

**Comment by Liemaeu** [comment] 2020-06-21 16:07
I tried it multiple times before, I also reimported the textures (some from cc0textures.com), but it didn't work, only a white ground.
Maybe it was something else, but I didn't change my Godot export settings.

**Comment by Liemaeu** [comment] 2020-06-21 16:11
Anyways, do you use Windows 10?
On Windows 10 is the Windows Subsystem for Linux available, maybe it is possible to compile at least the Linux version of the GDNative library on your pc.
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by Zylann** [comment] 2020-06-21 16:15
I use SCons to compile, and I would hope cross-compiling for Linux using that should work (even maybe using MinGW?). I just have no idea how to tell SCons to do such a thing.

**Comment by WilliamTambellini** [comment] 2020-09-04 17:46
> Ok, I made a simple script for this:
> https://github.com/Liemaeu/GDNative-linux-HeightMap/blob/master/GDNative-linux.sh
> (you need to place it into the addons/zylann.hterrain/ folder into your project folder, make it executable with chmod +x GDNative-linux.sh and run it with ./GDNative-linux.sh).

Any way to push that script in this repo ?

**Comment by Zylann** [comment] 2020-09-04 18:09
If you want to build yourself without having to just copy that script from here, maybe? Although the expectation is to have prebuilt binaries in the first place. What it does is relatively simple.
Also this is a script specifically for Linux.

**Comment by Zylann** [comment] 2020-09-04 18:57
Just quickly wrote GDNative instructions: https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/doc/main.md#gdnative

**Comment by capnm** [comment] 2020-09-04 19:55
That doesn't really help for human beings ;-) I've got it running on Linux roughly with steps:

cd addons/zylann.hterrain/native
git clone --recursive https://github.com/GodotNativeTools/godot-cpp -b 3.2
cd godot-cpp

cd godot_headers
git checkout 3.3

cd ..
scons platform=linux generate_bindings=yes

cd ..
scons platform=linux

tree bin/
```
bin/
├── linux
│   └── libhterrain_native.so
└── win64
    └── hterrain_native.dll
```

edit hterrain.gdnlib
```
[general]

singleton=false
load_once=true
symbol_prefix="godot_"
reloadable=false

[entry]

Windows.64="res://addons/zylann.hterrain/native/bin/win64/hterrain_native.dll"
X11.64="res://addons/zylann.hterrain/native/bin/linux/libhterrain_native.so"

[dependencies]

Windows.64=[  ]
X11.64=[  ]
```

**Comment by Zylann** [comment] 2020-09-04 20:02
> That doesn't really help human beings ;-)

@capnm if it doesnt then the official Godot docs doesnt either xD it's litterally a summary of the commands to run to build...
And you just pasted the same things so I dunno what you'd prefer to have in the doc

**Comment by capnm** [comment] 2020-09-04 20:23
I would prefer if you put a page somewhere with specific instructions on how to do this for xy OS for your add-on, rather than just referring to general pages that won't work for someone without proper background knowledge :-)

**Comment by capnm** [comment] 2020-09-04 20:30
Then a page with two paragraphs ;)

**Comment by capnm** [comment] 2020-09-05 00:21
Oh, I use clang++-10 so I've got it a little smaller.
(scons platform=linux use_llvm=yes)

Now I wonder how can your DLL be so small 8-()
522K bin/win64/hterrain_native.dll

The default makes the debug version, but target=release makes no relevant difference
`ls godot-cpp/bin`
128M libgodot-cpp.linux.debug.64.a
127M libgodot-cpp.linux.release.64.a

The scons target

```
clang++ -o bin/linux/libhterrain_native.so -shared src/gd_library.os
     src/image_utils.os -Lgodot-cpp/bin -lgodot-cpp.linux.release.64
```

makes

**40M** libhterrain_native.so*

and after running

`strip bin/linux/libhterrain_native.so`

I get

**2,7M** bin/linux/libhterrain_native.so*

I've only briefly tested that the stripped version works ... it didn't crashed my low-poly HTerrain demo :-)

**Comment by Zylann** [comment] 2020-09-05 00:24
I submitted a PR to the cpp bindings to fix it https://github.com/godotengine/godot-cpp/pull/452

**Comment by capnm** [comment] 2020-09-05 08:12
```
git diff SConstruct
diff --git a/addons/zylann.hterrain/native/SConstruct b/addons/zylann.hterrain/native/SConstruct
index 7488b3a..57b127e 100644
--- a/addons/zylann.hterrain/native/SConstruct
+++ b/addons/zylann.hterrain/native/SConstruct
@@ -61,7 +61,7 @@ elif env['platform'] == "linux":
         env.Append(CCFLAGS = ['-fPIC', '-g3', '-Og'])
         env.Append(CXXFLAGS = ['-std=c++17'])
     else:
-        env.Append(CCFLAGS = ['-fPIC', '-g', '-O3'])
+        env.Append(CCFLAGS = ['-fPIC', '-O3'])
         env.Append(CXXFLAGS = ['-std=c++17'])
```
3,6M bin/linux/libhterrain_native.so

```
clang++ -o src/image_utils.os -c -std=c++17 -fPIC -O3 -fPIC -I. -Igodot-cpp/godot_headers -Igodot-cpp/include -Igodot-cpp/include/core -Igodot-cpp/include/gen -Isrc src/image_utils.cpp
src/image_utils.cpp:301:17: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
            if (abs(i[ci] - texture_index_f) > 0.001f) {
                ^
src/image_utils.cpp:301:17: note: use function 'std::abs' instead
            if (abs(i[ci] - texture_index_f) > 0.001f) {
                ^~~
                std::abs
1 warning generated.
```

**Comment by Zylann** [comment] 2020-09-05 16:02
> warning: using integer absolute value function 'abs' when argument is of floating point type

![image](https://user-images.githubusercontent.com/1311555/92308888-f3a58580-ef98-11ea-995f-6b3272fbd5ca.png)
😕 

Also 3.6 Mb still sounds too much. I wonder if there is something else to bring it further down.

**Comment by capnm** [comment] 2020-09-05 17:33
IIRC it's so big because it was designed that way. The dynamic linker requires the C++ API stub. `strip` can also remove the debug information, but in C++ the linking process is complicated, I would just leave it without -g. Your Godot add-on is now the smallest of them all ;-)
![grafik](https://user-images.githubusercontent.com/4047289/92310379-037b9480-efae-11ea-9618-8d5866260565.png)

**Comment by Zylann** [comment] 2020-09-05 17:38
I'll consider adding an option to the C++ bindings to limit the generated classes then, that could be awesome to reduce size and compilation times

**Comment by WilliamTambellini** [comment] 2020-09-05 17:40
I agree with @capnm  : this plugin deserves a 4MB lib. Tks @Zylann

**Comment by Zylann** [comment] 2020-09-05 18:46
Just merged it into master

**Comment by FeralBytes** [comment] 2020-12-29 05:23
@Zylann now that you have added the Linux Native library, I think we can consider this bug closed. Thank you for your efforts.

**Closed** 2020-12-29 15:16 UTC
Labels: enhancement
