### ISSUE TITLE
Smooth tool flattening terrain

### ISSUE THREAD

**Issue by Mags0** [Zylann/godot_heightmap_plugin#78] opened 2019-04-20 22:02 UTC
At first everything works fine until I restart Godot, after that the smooth tool only works if the opacity is 100. Anything other than 100 causes it to smooth to 0 height and eventually flatten that part of the terrain. Why would this be?

**Comment by Zylann** [comment] 2019-04-27 16:57
I just tried this but could not reproduce. Do you have specific reproduction steps to make it happen?

**Comment by Mags0** [comment] 2019-04-28 21:41
Thankyou for getting back, I set up the terrain following your video [here](https://www.youtube.com/watch?v=eZuvfIHDeT4&), the only difference being that the data is a directory rather than a file. I have recorded the smoothing tool and how it behaves differently when the opacity is not on 100.
[TerrainSmooth.mp4.zip](https://github.com/Zylann/godot_heightmap_plugin/files/3125517/TerrainSmooth.mp4.zip)

**Comment by Zylann** [comment] 2019-06-06 21:41
Someone else had the issue at Isolation Game Jam, I'm not sure what causes it but it behaves as if the smooth operation was getting only zeroes from the heightmap (so it lowers the ground at faster rate the higher you are).

**Comment by Zylann** [comment] 2019-06-06 22:07
Turns out setting brush `opacity` to high value like 100 fixes it. Low values are broken.

**Comment by Zylann** [comment] 2019-06-11 18:12
Should be fixed by d3a550421f9cc9a3502525f5e69ec786218d5c37

**Closed** 2019-09-22 21:55 UTC
Labels: Fixed in master, bug
