### ISSUE TITLE
Now with official release of Godot 4.0, will this plugin be supporting it?

### ISSUE THREAD

**Issue by mrfisty** [Zylann/godot_heightmap_plugin#360] opened 2023-03-03 03:02 UTC

**Comment by Calinou** [comment] 2023-03-03 03:05
Duplicate of https://github.com/Zylann/godot_heightmap_plugin/issues/316.

**Comment by FreelyTian** [comment] 2023-03-08 14:48
That's not a duplicate, that's a reminder! Godot 4 is on stable now the overall porting process should have started some time ago, didn't it? I'm not trying to complain but this is the best terrain editor plugin out there in godot and I undestand that porting 3.5.x to 4.0 it's hard, pretty much of syntax was changed it's a complex plugin too. But There are much people here waiting, good luck to you guys in developing the port 😄

**Comment by LazyWizard** [comment] 2023-03-08 15:14
If you read the linked issue, you'll see that the plugin currently uses features that [didn't make it into Godot 4.0](https://github.com/Zylann/godot_heightmap_plugin/issues/316#issuecomment-1436074280), so it seems the port will need to wait for 4.1.

**Comment by FreelyTian** [comment] 2023-03-08 15:51
> If you read the linked issue, you'll see that the plugin currently uses features that [didn't survive into Godot 4.0](https://github.com/Zylann/godot_heightmap_plugin/issues/316#issuecomment-1436074280), so it seems the port will need to wait for 4.1.

Oh thx I didn't saw that, let's hope these things come with the 4.1

**Comment by Calinou** [comment] 2023-03-08 17:52
> That's not a duplicate, that's a reminder!

Remember that this plugin is provided for free with no obligation of support.

**Comment by Zylann** [comment] 2023-03-09 18:51
I had 4 reminders at this point, it's still a duplicate. Although I decided to pin the issue with most information, and close the others.

**Closed by Zylann** 2023-03-09 18:51 UTC

**Comment by FreelyTian** [comment] 2023-03-14 18:23
> I had 4 reminders at this point, it's still a duplicate. Although I decided to pin the issue with most information, and close the others.

Sorry, I didn't intend to be disrespectful with you guys
