### ISSUE TITLE
godot 4 is out... about after how many month we are going to get support for godot4?

### ISSUE THREAD

**Issue by bongblender** [Zylann/godot_heightmap_plugin#364] opened 2023-03-22 15:03 UTC
Besically, godot 4 is out... about after how many month we are going to get support for godot4? I want to start a project, but I am in confusion... should i wait or go with godot 3.5 ?

**Comment by ElsAr4e** [comment] 2023-03-22 16:19
You could also try other options: https://github.com/godotengine/godot-proposals/issues/6121#issuecomment-1465516387

**Comment by MGilleronFJ** [comment] 2023-03-22 17:04
This is a duplicate of #316. The plugin is currently being ported. You will have to wait for a bit. I imagine it won't take months tho.

**Closed as completed** 2023-03-22 18:38 UTC
