### ISSUE TITLE
No Terrain Data saved on disk

### ISSUE THREAD

**Issue by pietru2004** [Zylann/godot_heightmap_plugin#425] opened 2024-01-21 20:31 UTC
**Describe the bug**
When I set data directory it seams like HTerrainData is not saved to disk...
When I launch game I can see no terrain.
When I reload editor I can see prompt about missing resource.

**Environment**
- OS: Windows
- Godot version 4.2.1
- Plugin version 1.7.2
- Renderer used: Forward+

**Comment by Zylann** [comment] 2024-01-21 22:15
> When I set data directory it seams like HTerrainData is not saved to disk...

This alone is not enough for it getting saved. You have to save the scene too after doing that.
See also https://github.com/Zylann/godot_heightmap_plugin/issues/232

**Comment by pietru2004** [comment] 2024-01-22 14:30
I have downloaded 1.7.3 dev and it seamed to fix it... Also I did safe scene after that and error I was getting was that resource type was unrecognized or something like that

**Comment by pietru2004** [comment] 2024-01-22 14:32
I guess this is bug is category of it does not work and I don't know why, it works and I don't know why...

**Comment by Zylann** [comment] 2024-01-22 18:42
> resource type was unrecognized or something like that

Yep that's Godot's heisenbug in custom resource loaders

**Comment by Fromeyer** [comment] 2024-01-30 01:08
I just downloaded this today and all was working well, except the following. Every time I save and quit, the data directory is gone and the terrain is gone. All the textures are there but the terrain is gone. When I try and fix the dependency the folder is there but there is no data in it. As soon as I re-import my heightmap it is textured just the way I left it. The second thing is the texture importer window is way too big and I can't access all the buttons on the bottom. It moves left or right but I can't make it detach or any smaller.

**Comment by Zylann** [comment] 2024-01-30 02:07
Please refer to https://github.com/Zylann/godot_heightmap_plugin/issues/232, this issue is a duplicate. I'm sorry it keeps happening randomly but sadly I haven't the faintest idea why it happens have never been able to reproduce it. I believe it's a bug in Godot somehow.

>  The second thing is the texture importer window is way too big

That bug has surfaced in Godot 4.2 and has been fixed in the main branch, you may download it from the repo instead of the asset library.

**Comment by A13ks4** [comment] 2024-02-10 09:02
I have the same problem on 1.7.2 version. Terrain doesn't load when i start the game, but it's not every time.
Here is the error
![error](https://github.com/Zylann/godot_heightmap_plugin/assets/37981833/ad0b050b-8154-4eaf-800a-7488345001b7)

**Comment by Zylann** [comment] 2024-02-10 16:46
I'm going to close this because that remains a duplicate of https://github.com/Zylann/godot_heightmap_plugin/issues/232
I explained a lot of times now why this is still not fixed...

**Closed** 2024-02-10 16:46 UTC
