### ISSUE TITLE
Terrain directory always empty - Data not saving

### ISSUE THREAD

**Issue by Anemony22** [Zylann/godot_heightmap_plugin#81] opened 2019-05-06 13:42 UTC
It is entirely possible I'm just doing this wrong and don't know the steps to take to save the terrain file into the chosen directory, but for the moment I can't save it manually, and it doesn't save automatically. I have only started using this as of v1.1, and in the changelog it says you removed the save and load menu, but when I tired v1.0 it also doesn't work.

My scene is as simple as it can be, with a pretty much flat HTerrain, a camera and an omnilight, yet I can't launch the scene without receiving the following errors. I have made the terrain data file and put it in a folder named terrain, but it doesn't seem to be doing anything.

Any help would be greatly appreciated.

Also, my apologies if this is the same issue as in issue #75 but the log and details seemed different enough to warrant a separate issue.

```
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:32086]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
Running: C:\Program Files (x86)\Godot\Godot_v3.0.6-stable_win64.exe --path C:/Users/**/Documents/Godot/Terrain%20Testing --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 3268 --position 448,240 res://Node.tscn
running cmdline: "C:\Program Files (x86)\Godot\Godot_v3.0.6-stable_win64.exe" "--path" "C:/Users/**/Documents/Godot/Terrain%20Testing" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "3268" "--position" "448,240" "res://Node.tscn"
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
ERROR: No loader found for resource: res://terrain/data.hterrain
   At: core/io/resource_loader.cpp:186
ERROR: poll: res://Node.tscn:5 - Parse Error: [ext_resource] referenced nonexistent resource at: res://terrain/data.hterrain
   At: scene/resources/scene_format_text.cpp:439
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:149
ERROR: Failed loading resource: res://Node.tscn
   At: core/io/resource_loader.cpp:186
ERROR: Failed loading scene: res://Node.tscn
   At: main/main.cpp:1688
Nothing read: Invalid argument
ERROR: read: Server disconnected!

   At: drivers/windows/stream_peer_tcp_winsock.cpp:203
WARNING: cleanup: ObjectDB Instances still exist!
     At: core/object.cpp:1989
``` 

--
Anemony

**Comment by Goose011** [comment] 2019-05-06 13:59
Let me provide some more details as that might have been unclear. I have chosen the directory, which creates the blank plane. However there are no manual save/load options, saving the scene doesn't make the data.hterrain file, if I create the .tres file then that does nothing at all (it won't let me select it like it allows you to do in your demonstration video) and putting it into the selected folder also does nothing.

Hope that provides a bit more insight into the problem.

**Comment by alexwbc** [comment] 2019-06-03 08:17
Same issue applies to me: terrain work fine with 3.1.1 stable but don't work anymore with newer version of Godot.

''' ERROR: No loader found for resource: res://terrain/data.hterrain

**Comment by Zylann** [comment] 2019-06-11 15:35
This error implies that Godot did not register the terrain resource loader properly... Maybe it was broken in master?

**Comment by MegaMech** [comment] 2019-06-18 23:43
I'm having the same issue.
When I restart Godot 3.1.1 I get an "error loading dependency": data.hterrain
If I click open anyway the "data directory" box is empty.
I tried creating a new txt file and renaming it to data.hterrain, to try and make it work. I also ran Godot as an administrator. Still no go for me. When I run the project I get:  drivers/unix/net_socket_posix.cpp:190 - Socket error: 10054


 No loader found for resource: res://Game/terrain/data.hterrain
 No loader found for resource: res://Game/terrain/data.hterrain
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://Game/terrain/data.hterrain
 editor/editor_data.cpp:564 - Index p_idx=1 out of size (edited_scene.size()=1)
Switch Scene Tab
 No loader found for resource: res://Game/terrain/data.hterrain
 No loader found for resource: res://Game/terrain/data.hterrain
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://Game/terrain/data.hterrain
Create HeightMap
HTerrainCollider: creating body
Set new data [Object:null]
Setting chunk size to 16
Chunk size snapped to 16
Enter world
HTerrainCollider: terrain data not set yet
Enter tree
Transform changed
HTerrainCollider: terrain data not set yet
Updating terrain material params

**Comment by Zylann** [comment] 2019-06-18 23:51
Is it Godot with GLES2 or GLES3? (should not matter but who knows).
Does anyone have reproduction steps? Because the plugin worked fine to build a full game for someone at a jam with Godot 3.1.1. All I see from the logs is that Godot did not register the terrain loader for some reason, but I don't know why.

**Comment by MegaMech** [comment] 2019-06-19 00:01
K, I'll try and get you  some more substantial information.
I was able to get 1.0 to work by manually creating the .png files. Possibly in combination with the save and load buttons.

I get assertion failed errors. Could it be a permissions problem where windows is denying your plugin write access?

**Comment by Zylann** [comment] 2019-06-19 00:02
Any error occurring first from the moment you start an empty project can be useful to diagnose the origin of the problem.

**Comment by MegaMech** [comment] 2019-06-19 00:20
Strange... It's working now. It was able to load the premade files in a terrain folder.
I created a second HTerrain object with it's own folder and this time it was able to create all the files.
There were some errors and the terrain disappeared but when I restarted Godot it was there again, and seems to be saving properly now.
So weird... I'm not working off of my C:\ drive either.
I've pasted my entire output below

Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:31045]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
 Signal 'resolution_changed' is already connected to given method '_on_data_resolution_changed' in that object.
 Signal 'region_changed' is already connected to given method '_on_data_region_changed' in that object.
 Signal 'progress_notified' is already connected to given method '_on_data_progress_notified' in that object.
 Signal 'map_changed' is already connected to given method '_on_data_map_changed' in that object.
 Signal 'map_added' is already connected to given method '_on_data_map_added' in that object.
 Signal 'map_removed' is already connected to given method '_on_data_map_removed' in that object.
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Updating terrain material params
Updating terrain material params
Edit Null
Edit [Spatial:23499]
Edit Null
Edit [Spatial:23499]
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:22392]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
 res://addons/zylann.hterrain/hterrain_data.gd:265 - Assertion failed.
 Expected PoolRealArray or float Image.
Create grid for lod 0, 0x0
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:31045]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
 res://addons/zylann.hterrain/hterrain_data.gd:265 - Assertion failed.
 Expected PoolRealArray or float Image.
Create grid for lod 0, 0x0
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
Destroy HTerrain
Destroy HTerrainCollider
No data in channel 0[0]
No data in channel 1[0]
No data in channel 2[0]
No data in channel 3[0]
No data in channel 5[0]
HTerrainCollider: setting up heightmap
 res://addons/zylann.hterrain/hterrain_data.gd:265 - Assertion failed.
 Expected PoolRealArray or float Image.
WARNING: setting twice the same terrain directory??
Set data_directory
No data in channel 0[0]
No data in channel 1[0]
No data in channel 2[0]
No data in channel 3[0]
No data in channel 5[0]
HTerrainCollider: setting up heightmap
 res://addons/zylann.hterrain/hterrain_data.gd:265 - Assertion failed.
 Expected PoolRealArray or float Image.
WARNING: setting twice the same terrain directory??
Set data_directory
Edit Null
Edit [Spatial:28694]
Edit Null
Edit [Spatial:28694]
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:22392]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
 res://addons/zylann.hterrain/hterrain_data.gd:265 - Assertion failed.
 Expected PoolRealArray or float Image.
Create grid for lod 0, 0x0
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:31045]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
 res://addons/zylann.hterrain/hterrain_data.gd:265 - Assertion failed.
 Expected PoolRealArray or float Image.
Create grid for lod 0, 0x0
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
Destroy HTerrain
Destroy HTerrainCollider
 res://addons/zylann.hterrain/hterrain_brush.gd:628 - Assertion failed.
 res://addons/zylann.hterrain/tools/plugin.gd:369 - Invalid get index 'channel' (on base: 'Nil').

**Comment by Zylann** [comment] 2019-06-19 00:28
Could you rather paste the output of the system console? In my experience the in-editor console contains less information.

**Comment by MegaMech** [comment] 2019-06-19 01:01
Do you mean the command prompt window that opens with Godot? Or the debugger errors tab?

**Comment by Zylann** [comment] 2019-06-19 01:04
The command prompt that opens with Godot. You should be able to select text in it.
If you are on Windows 10, just drag the mouse to select and right-click will put selected text in your clipboard.
If you are on Windows 7, clicking the top-left icon of the window opens a menu with "select" option in it.
On OSX and Linux it should be selectable straight away.

**Comment by MegaMech** [comment] 2019-06-19 01:12
For some reason when I was left and right clicking on the CMD no mark and no right click menu was popping up. And then it started working. My left mouse button is kinda broken...
This is near the start after load:
WARNING: load: Loaded resource as image file, this will not work on export: 'res
://Game/terrain/normal.png'. Instead, import the image file as an Image resource
 and load it normally as a resource.
     At: core/image.cpp:1746

Here's around what happens when I create a new heightmap. This time it seems to be working fine. Code can't fix itself... So strange it wasn't working, than mostly working, and now no problemo.

Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:22609]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
erasing K:/source/Godot/shipgame/.mono/metadata/scripts_metadata.editor
Running: K:\source\Godot_v3.1.1-stable_mono_win64\Godot_v3.1.1-stable_mono_win64
.exe --path K:/source/Godot/shipgame --remote-debug 127.0.0.1:6007 --allow_focus
_steal_pid 6256 --position 448,240
OpenGL ES 3.0 Renderer: Radeon RX 580 Series
erasing C:/Users/Alex/AppData/Roaming/Godot/mono/mono_logs/2019_06_13 16.36.49 (
6300).txt
Mono: Logfile is: C:\Users\Alex\AppData\Roaming/Godot/mono/mono_logs/2019_06_18
19.01.36 (6096).txt
_upload_region was used but the texture is not created yet. The map 0[0] will be
 uploaded entirely.
Updating all vertical bounds... (32x32 chunks)
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:1403]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Enter world
Enter tree
AREAS
(-2, 0, -21.04794)
(50.09587, 0, 21.04794)
Transform changed
Updating terrain material params
Timer
Edit Null
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:22609]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
Create HeightMap
HTerrainCollider: creating body
Enter world
HTerrainCollider: terrain data not set yet
Enter tree
Edit [Spatial:429128]
Transform changed
HTerrainCollider: terrain data not set yet
Updating terrain material params
Edit Null
Edit [Spatial:429128]
Set new data [Resource:432229]
Connecting new HeightMapData
Loading default data
HeightMapData::set_resolution 512
Resizing height[0]...
Resizing normal[0]...
Resizing splat[0]...
Resizing color[0]...
Resizing global_albedo[0]...
Updating all vertical bounds... (32x32 chunks)
HTerrainCollider: setting up heightmap
_upload_region was used but the texture is not created yet. The map 0[0] will be
 uploaded entirely.
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Updating terrain material params
_upload_region was used but the texture is not created yet. The map 1[0] will be
 uploaded entirely.
_upload_region was used but the texture is not created yet. The map 3[0] will be
 uploaded entirely.
_upload_region was used but the texture is not created yet. The map 2[0] will be
 uploaded entirely.
_upload_region was used but the texture is not created yet. The map 5[0] will be
 uploaded entirely.
Menu item selected 1
Done
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:22609]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:432229]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
Destroy HTerrain
Destroy HTerrainCollider
HTerrainCollider: setting up heightmap

**Comment by Zylann** [comment] 2019-09-22 21:57
I believe this was actually fixed in Godot master branch, now `class_name` can appear before `extends`.

**Comment by jarrellmark** [comment] 2019-09-27 04:27
Hi thanks for the great addon. I'm having the same problem on Ubuntu 18.04 using godot 3.1.1.stable.official from Steam.

Steps to reproduce are:

1. Opened my existing project which did have some things in it already. (I already added the addon to the addon directory and have activated it)
2. Make a new scene
3. Add a 3d spatial object
4. Add an HTerrain as a child of the Spatial
5. Set data dir to a new folder Terrain_Test
6. Save the scene as Terrain_test.tscn
7. Exit Godot

After this, the Terrain_Test directory is empty. I'm unable to open Terrain_test.tscn again properly since all the files are missing.

Here's the logs:

$ "./.local/share/Steam/steamapps/common/Godot Engine/godot.x11.opt.tools.64"
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
Editing project: /home/mark/Projects/2019/10_Kite_Game/Version_01 (::home::mark::Projects::2019::10_Kite_Game::Version_01)
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
(base) mark@mark-ThinkPad-E450:~$ HTerrain plugin Enter tree
ERROR: build: Condition ' O == E ' is true. Continuing..:
   At: core/math/quick_hull.cpp:401.
ERROR: build: Condition ' O == E ' is true. Continuing..:
   At: core/math/quick_hull.cpp:401.
ERROR: build: Condition ' O == __null ' is true. Continuing..:
   At: core/math/quick_hull.cpp:402.
Create HeightMap
HTerrainCollider: creating body
Enter world
HTerrainCollider: terrain data not set yet
Enter tree
Edit [Spatial:23694]
Transform changed
HTerrainCollider: terrain data not set yet
Updating terrain material params
Edit Null
Edit [Spatial:23694]
Set new data [Resource:25946]
Connecting new HeightMapData
Loading default data
HeightMapData::set_resolution 512
Resizing height[0]...
Resizing normal[0]...
Resizing splat[0]...
Resizing color[0]...
Resizing global_albedo[0]...
Updating all vertical bounds... (32x32 chunks)
HTerrainCollider: setting up heightmap
_upload_region was used but the texture is not created yet. The map 0[0] will be uploaded entirely.
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Updating terrain material params
_upload_region was used but the texture is not created yet. The map 1[0] will be uploaded entirely.
_upload_region was used but the texture is not created yet. The map 3[0] will be uploaded entirely.
_upload_region was used but the texture is not created yet. The map 2[0] will be uploaded entirely.
_upload_region was used but the texture is not created yet. The map 5[0] will be uploaded entirely.
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:25946]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
Create HeightMap
HTerrainCollider: creating body
Set new data [Resource:25946]
Connecting new HeightMapData
HTerrainCollider: setting up heightmap
Create grid for lod 0, 32x32
Create grid for lod 1, 16x16
Create grid for lod 2, 8x8
Create grid for lod 3, 4x4
Create grid for lod 4, 2x2
Create grid for lod 5, 1x1
Set data done
Setting chunk size to 16
Chunk size snapped to 16
Destroy HTerrain
Destroy HTerrainCollider
HTerrain plugin Exit tree
Edit Null
Exit world
Destroy HTerrain
Destroy HTerrainCollider

Thanks

**Comment by jarrellmark** [comment] 2019-09-27 04:38
Nvm, I tried again using the current master branch of godot heighmap plugin from https://github.com/Zylann/godot_heightmap_plugin/tree/2d2a8d760527e4e301707de28171e415139c095a .

That fixed the problem

**Comment by Zylann** [comment] 2019-09-27 12:09
I recently worked around #101 in the master branch which could have been another cause of terrain not saving.
However, from what the first post of this issue shows, the error is different and was actually caused by `class_name` order, which was fixed in Godot's master branch. So I believe this issue can be closed.

**Closed** 2020-03-28 16:00 UTC
Labels: bug
