### ISSUE TITLE
Grass not placed correctly when height of terrain is scaled

### ISSUE THREAD

**Issue by ThunderFD** [Zylann/godot_heightmap_plugin#83] opened 2019-05-30 19:52 UTC
if you scale the terrain on the y axis, which I did (I did 0.5 on x,y,z before I started) grass will not be planted on the surface, since the grass position doesn't seem to be scaled vertically!

edit: with height I mean the "map scale" field

**Comment by ThunderFD** [comment] 2019-05-30 19:58
here's a screenshot:
![image](https://user-images.githubusercontent.com/17814079/58660558-01944180-8326-11e9-9ea1-5f906ca09f71.png)

**Comment by ThunderFD** [comment] 2019-05-30 20:00
oops, same issue as #74

**Comment by Zylann** [comment] 2019-06-11 15:20
Duplicate of #74 indeed, I noticed it during a game jam too. Will have a look in a moment.

**Closed by Zylann** 2019-06-11 15:20 UTC

**Comment by ThunderFD** [comment] 2019-06-11 15:25
cool! I fixed it in #84 - you could just merge that
