### ISSUE TITLE
Collider not working any more

### ISSUE THREAD

**Issue by darrylryan** [Zylann/godot_heightmap_plugin#97] opened 2019-09-19 13:53 UTC
With the latest godot master the collider seems to be broken

**Comment by Zylann** [comment] 2019-09-20 19:23
How is it broken? If it is that's a compatibility breakage, or a bug, and should be reported to Godot.

**Comment by darrylryan** [comment] 2019-09-22 12:59
The characters just fall through the terrain now... not sure why as it seems to be running the collider creation code and printing the debug message OK.

**Comment by Zylann** [comment] 2019-09-22 13:18
I did a test and the hits actually get reported higher than ground:

![image](https://user-images.githubusercontent.com/1311555/65388306-e4a3d400-dd43-11e9-9da4-4afe840d307f.png)

**Comment by darrylryan** [comment] 2019-09-22 14:42
That makes sense... then my character falls through because it starts off below that layer...

It seems to be specific to the terrain collider though since it works fine when I add colliders to meshes in the editor.

**Comment by Zylann** [comment] 2019-09-22 14:46
I am slowly checking old versions of the engine. This bug was already there in `eaaff9da3178fa515a0f051fda932c1dd04d53db`, which is like, 2 months ago

**Comment by Zylann** [comment] 2019-09-22 15:22
This was likely caused by `e4dea0595aae76de254502bca714b9e54e46b74a`

**Comment by darrylryan** [comment] 2019-09-22 15:38
So do we just need to shift it down a bit after creation or do we need to change the AABB?

**Comment by Zylann** [comment] 2019-09-22 15:41
First I need to know if that's something worth fixing in Godot (since it's compatibility breakage), if not then will need to add an `if` to check if it's Godot 3.2 or later and apply a different transformation here: https://github.com/Zylann/godot_heightmap_plugin/blob/4d076a2f712317f146942b785c5192084174280d/addons/zylann.hterrain/hterrain_collider.gd#L97

**Comment by darrylryan** [comment] 2019-09-22 17:54
I've changed mine to the following and that does indeed solve the issue. I wonder why they changed it, either seems fine to me, as long as its documented.
` var trans = Transform(Basis(), 0.5 * Vector3(width, _**0**_, depth) + Vector3(0, aabb.position.y, 0)) `

**Comment by BastiaanOlij** [comment] 2019-09-23 10:32
@Zylann can this be caused by you adjusting the height because Godot originally didn't, and now that I make Godot adjust the height you're double correcting?

**Comment by BastiaanOlij** [comment] 2019-09-23 10:34
> 
> 
> This was likely caused by `e4dea0595aae76de254502bca714b9e54e46b74a`
> https://github.com/godotengine/godot/pull/28326/files#diff-51c3f48359856e1f53cfeb65f82a859fR62
> 
> Before, the shape was centered on origin based on its total AABB. Now the vertical centering is different...

Indeed, it now uses the coordinates as is. So if in your height data you specify a height of 1, it is now at 1 above the origin of the heightfield. Not moved by whatever to center it.

**Comment by Zylann** [comment] 2019-09-23 12:44
@BastiaanOlij yes I was correcting that in my code (and will still need to correct that to remain compatible with previous versions). It's no big deal really, I just wanted to be sure what we want for the Godot API because objectively, that's currently a compatibility breakage.
On the other hand we could consider the previous behavior as unexpected, I assume the new behavior is what to expect from the PhysicsServer API in general?

**Comment by BastiaanOlij** [comment] 2019-09-24 10:16
@Zylann seeing the heightmap logic was pretty hidden up until us introducing the heightmap shape I think we can get away with it. I really don't get why bullet didn't deal with this. 

I understand the technical reason for more efficient collision detection if the shape is centered but it would be easy to adjust the positioning in the core just like we do now. That to me is the more intuitive solution without giving up performance. Very often heightmaps are placed on the ground with values between 0 and max-height, if the whole shape then gets pushed down, I think that will have tripped up many people.

**Comment by Zylann** [comment] 2019-09-24 17:53
Should be fixed by f792c2725ff36489bca2b1d40d9a8232f7295b3a

**Comment by David-Ochoa** [comment] 2019-10-08 16:10
I'm retaking my project and downloaded version 3.2 alpha 1, it changed again, I need to use this to have it working:
`trans = Transform(Basis(), 0.5 * Vector3(width, 0, depth))`

**Comment by Zylann** [comment] 2019-10-08 17:44
Wow, how come it changed again Oo I wonder which commit did that

**Comment by Zylann** [comment] 2019-10-08 18:06
Should be fixed again in df55cfefb3252a401e7c871bc975528b75854cd6

**Closed** 2019-10-11 00:00 UTC
Labels: Fixed in master, bug

**Comment by randy-girard** [comment] 2019-12-22 14:59
I seem to have this issue happening. I added a shape with a collision shape. My character doesn't collide where the terrain is, but rather quite a bit below the terrain. I have this chunk in the collider.gd file
```
	if v.major == 3 and v.minor <= 1 and v.patch <= 1:
		# Bullet centers the shape to its overall AABB so we need to move it to match the visuals
		trans = Transform(Basis(), 0.5 * Vector3(width, height, depth) + Vector3(0, aabb.position.y, 0))
	else:
		# In 3.2, vertical centering changed.
		# https://github.com/godotengine/godot/pull/28326
		trans = Transform(Basis(), 0.5 * Vector3(width, 0, depth))
```

Is this correct and I am just doing something dumb?

**Comment by randy-girard** [comment] 2019-12-22 15:05
OK, nevermind. I just upgraded to 3.2 alpha and it works. Sorry for the confusion!
